const images = {
  applogo: require('../assets/images/largeimages/clearchoicelogo.png'),
  bbblogo: require('../assets/images/largeimages/bbb-accredited-business.png'),
  certifiedfirmlogo: require('../assets/images/largeimages/iicrc-certified.png'),
  isnlogo: require('../assets/images/largeimages/isnetworld-member.png'),
  loginbg: require('../assets/images/largeimages/loginbg.png'),
  loginlogo: require('../assets/images/largeimages/loginlogo.png'),

  // Icons
  smsicon: require('../assets/images/Icons/sms.png'),
  lockicon: require('../assets/images/Icons/lock.png'),
  down: require('../assets/images/Icons/arrow-down.png'),
  calendar: require('../assets/images/Icons/calendar.png'),
  adminIcon: require('../assets/images/Icons/Admin.png'),
  clock: require('../assets/images/Icons/clock.png'),

  home:require('../assets/images/Icons/home2.png'),
  rightArrow:require('../assets/images/Icons/arrowright.png'),
  calandertick:require('../assets/images/Icons/calendar-tick.png'),
  message:require('../assets/images/Icons/msg.png'),
  document:require('../assets/images/Icons/document-text.png'),
  note:require('../assets/images/Icons/note.png'),
  logout:require('../assets/images/Icons/export.png'),
  arrowleft:require('../assets/images/Icons/arrow-left.png'),
  notification:require('../assets/images/Icons/notification.png'),
  notificationicons:require('../assets/images/Icons/notificationicons.png'),
  notificationbell:require('../assets/images/Icons/nbell.png'),
  firstline:require('../assets/images/Icons/firstline.png'),
  profileservice:require('../assets/images/Icons/services.png'),
  profileservicelog:require('../assets/images/Icons/servicelog.png'),
  smsgray:require('../assets/images/Icons/smsgray.png'),
  callgray:require('../assets/images/Icons/callgray.png'), 
  adminicon:require('../assets/images/Icons/adminicon.png'),
};
export default images;
